In [34]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error,make_scorer

X, y = np.random.rand(2,200)
clf = SVR()

ys = []

def MSE(y_true,y_pred):
    global ys
    ys.append(y_pred)
    mse = mean_squared_error(y_true, y_pred)
    return mse

def scorer():
    return make_scorer(MSE, greater_is_better=False)

n_splits = 3 
cv = GridSearchCV(clf, {'degree':[1,2,3]}, scoring=scorer(), cv=n_splits)
cv.fit(X.reshape(-1, 1), y)

GridSearchCV(cv=3, estimator=SVR(), param_grid={'degree': [1, 2, 3]},
             scoring=make_scorer(MSE, greater_is_better=False))

In [20]:
import numpy as np
from sklearn.model_selection import GridSearchCV,TimeSeriesSplit
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error,make_scorer

X, y = np.random.rand(2,200)
clf = SVR()

ys = []

def MSE(y_true,y_pred):
    global ys
    ys.append(y_pred)
    mse = mean_squared_error(y_true, y_pred)
    return mse

def scorer():
    return make_scorer(MSE, greater_is_better=False)

# Define the initial training size (e.g., 70% of the data)
initial_train_size = int(0.9 * len(y))

# Create the time series split for cross-validation
tscv = TimeSeriesSplit(n_splits=len(y) - initial_train_size, test_size=1, gap=0, max_train_size=None)

cv = GridSearchCV(clf, {'degree':[1,2,3]}, scoring=scorer(), cv=tscv)
cv.fit(X.reshape(-1, 1), y)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=20, test_size=1),
             estimator=SVR(), param_grid={'degree': [1, 2, 3]},
             scoring=make_scorer(MSE, greater_is_better=False))

In [27]:
import numpy as np
from sklearn.model_selection import GridSearchCV,TimeSeriesSplit
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error,make_scorer

X, y = np.random.rand(2,200)
clf = GradientBoostingRegressor()

ys = []

def MSE(y_true,y_pred):
    global ys
    ys.append(y_pred)
    mse = mean_squared_error(y_true, y_pred)
    return mse

def scorer():
    return make_scorer(MSE, greater_is_better=False)

# Define the initial training size (e.g., 70% of the data)
initial_train_size = int(0.9 * len(y))
# Set up the parameter grid for grid search
param_grid = {
    'n_estimators': [50, 100],
    'learning_rate': [0.1, 0.3],
    'subsample': [1],
    'max_depth': [3, 8],
    'min_samples_leaf': [5]
}

# Create the time series split for cross-validation
tscv = TimeSeriesSplit(n_splits=len(y) - initial_train_size, test_size=1, gap=0, max_train_size=None)

cv = GridSearchCV(clf, param_grid,scoring=scorer(),  cv=tscv)
cv.fit(X.reshape(-1, 1), y)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=20, test_size=1),
             estimator=GradientBoostingRegressor(),
             param_grid={'learning_rate': [0.1, 0.3], 'max_depth': [3, 8],
                         'min_samples_leaf': [5], 'n_estimators': [50, 100],
                         'subsample': [1]},
             scoring=make_scorer(MSE, greater_is_better=False))

In [28]:
ys

[array([0.52608133]),
 array([0.52301515]),
 array([0.63059287]),
 array([0.59737764]),
 array([0.60018275]),
 array([0.52561363]),
 array([0.56422876]),
 array([0.72678739]),
 array([0.49464161]),
 array([0.48087656]),
 array([0.38030541]),
 array([0.55789272]),
 array([0.56439918]),
 array([0.6105538]),
 array([0.59519131]),
 array([0.44133057]),
 array([0.42736059]),
 array([0.47110014]),
 array([0.58568961]),
 array([0.44617147]),
 array([0.53692342]),
 array([0.45544443]),
 array([0.64152824]),
 array([0.62977493]),
 array([0.59064912]),
 array([0.50935549]),
 array([0.63144861]),
 array([0.75509128]),
 array([0.51195047]),
 array([0.42981643]),
 array([0.33704814]),
 array([0.562334]),
 array([0.57110366]),
 array([0.62043227]),
 array([0.59282165]),
 array([0.43455637]),
 array([0.36738285]),
 array([0.47135726]),
 array([0.580798]),
 array([0.42409046]),
 array([0.54190758]),
 array([0.44733225]),
 array([0.66035237]),
 array([0.62436414]),
 array([0.59000667]),
 array([0.50504

In [39]:
import numpy as np
from sklearn.model_selection import GridSearchCV,TimeSeriesSplit
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import mean_squared_error,make_scorer

X, y = np.random.rand(2,200)
y = np.where(y < 0.5, 'LONG', 'SHORT')
clf = GradientBoostingClassifier()

ys = []

def Acc_Score(y_true,y_pred):
    global ys
    ys.append(y_pred)
    acc = accuracy_score(y_true, y_pred)    
    return acc

def scorer():
    return make_scorer(Acc_Score, greater_is_better=False)

# Define the initial training size (e.g., 70% of the data)
initial_train_size = int(0.9 * len(y))
# Set up the parameter grid for grid search
param_grid = {
    'n_estimators': [50, 100],
    'learning_rate': [0.1, 0.3],
    'subsample': [1],
    'max_depth': [3, 8],
    'min_samples_leaf': [5]
}

# Create the time series split for cross-validation
tscv = TimeSeriesSplit(n_splits=len(y) - initial_train_size, test_size=1, gap=0, max_train_size=None)

cv = GridSearchCV(clf, param_grid,scoring=scorer(),  cv=tscv)
cv.fit(X.reshape(-1, 1), y)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=20, test_size=1),
             estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.1, 0.3], 'max_depth': [3, 8],
                         'min_samples_leaf': [5], 'n_estimators': [50, 100],
                         'subsample': [1]},
             scoring=make_scorer(Acc_Score, greater_is_better=False))

In [41]:
ys

[array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['LONG'], dtype='<U5'),
 array(['SHORT'], dtype='<U5'

In [6]:
import pandas as pd
cv_results = pd.DataFrame(cv.cv_results_)

In [10]:
ys

[array([0.59907308, 0.56901707, 0.57976693, 0.4170793 , 0.55474692,
        0.41568038, 0.55678635, 0.39583892, 0.5554577 , 0.40943661,
        0.59239213, 0.39581156, 0.38861099, 0.41345653, 0.51169417,
        0.39611623, 0.54914364, 0.436533  , 0.5840385 , 0.44767445,
        0.56609411, 0.5288404 , 0.43757299, 0.45591477, 0.41764212,
        0.39577575, 0.39084568, 0.52334113, 0.45175885, 0.38821067,
        0.57259609, 0.4057003 , 0.41523069, 0.55545707, 0.52509665,
        0.55728941, 0.39463887, 0.42489871, 0.41112356, 0.32234819,
        0.56153227, 0.46609387, 0.5769538 , 0.42368086, 0.36987418,
        0.48982317, 0.55691632, 0.56696779, 0.45936455, 0.57578839,
        0.46970564, 0.39717186, 0.55555736, 0.4659587 , 0.41693831,
        0.5984012 , 0.43669222, 0.44370268, 0.41110728, 0.57619458,
        0.38830987, 0.60087636, 0.60057431, 0.58383876, 0.4166704 ,
        0.34344128, 0.54865149]),
 array([0.5757995 , 0.60725323, 0.49348671, 0.56239176, 0.5434311 ,
        0.6253